### ISSUE TITLE
Manuscript Error:

### ISSUE THREAD

**Issue by st--** [BayesianModelingandComputationInPython/BookCode_Edition1#102]
# Description
The sentence about the New York Times Election Needle seems to be missing something at the end.

**Reference**
p.284, "Animation" paragraph.

 

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by canyon289** [comment]
Ah yes youre right, the missing part is `the uncertainty in the estimation of which candidate would ultimately win.`

**Comment by canyon289** [comment]
Closed by https://github.com/BayesianModelingandComputationInPython/BookCode_Edition1/pull/123
