### ISSUE TITLE
Update figure 3.3

### ISSUE THREAD

**Issue by aloctavodia** [BayesianModelingandComputationInPython/BookCode_Edition1#106]
In the description "vertical lines" are mentioned, but not visible in the plots.

![Screenshot from 2022-01-31 09-17-14](https://user-images.githubusercontent.com/1338958/151753219-58817234-a882-46e3-9ddb-e9b54a49de0e.png)

## Author Section
Do not close until

- [ ] Added to Errata
- [ ] Fixed in Open Access
- [ ] Fixed in latex source

**Comment by canyon289** [comment]
Closed by https://github.com/BayesianModelingandComputationInPython/BookCode_Edition1/pull/123
