### ISSUE TITLE
Manuscript Error:

### ISSUE THREAD

**Issue by tpogden** [BayesianModelingandComputationInPython/BookCode_Edition1#133]
# Description

```diff
- we introduce these concepts and methods, many, which will be further explored 
+ we introduce these concepts and methods, many of which will be further explored 
```

**Reference**
https://bayesiancomputationbook.com/markdown/chp_01.html

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by aloctavodia** [comment]
thanks @tpogden!
