### ISSUE TITLE
SARIMAX - Time Series Models

### ISSUE THREAD

**Issue by scroobiustrip** [BayesianModelingandComputationInPython/BookCode_Edition1#134]
Hey, thanks once again for the great book - I was just revisiting the section on the Tensorflow Probability implementation of SARIMAX in [Chapter 6](https://bayesiancomputationbook.com/notebooks/chp_06.html), I have a couple quick questions:

1) Is it possible to use / include a demo of how you'd make out of sample forecast predictions using the SARIMAX models? (Probably requires more effort, but similar to the forecast examples given using the STS models at the end?)

2) While it's stated that we can't combine the `seasonal_order` with the `design_matrix` - is it possible to model external regressors (e.g. holidays, covariates etc) in addition to using the `fourier_seasonality()` basis function, and just add a couple extra columns to the design matrix, or is something more clever / sophisticated required?

Many thanks again!

**Comment by junpenglao** [comment]
1. It is actually exercise 6H15 - we are in the process of release the solution of the exercise, please stay tuned
2. It is totally possible to combine SARIMA with external regressor, it just that it gets confusing, and many implementations actually opt to disallow it. We will update the text "Note that we can have either seasonal (SARIMA) or exogenous regressors (ARIMAX) but not both." in the 2nd to clarify this point.

**Comment by scroobiustrip** [comment]
Oh fantastic (look forward to going through them!) and okay great, so is it just a case of fitting a Normal prior over a holiday beta and just passing in the index of 1's and 0's to the design matrix?

Or will some modifying be required to remove the code that sets the seasonal.period

**Comment by scroobiustrip** [comment]
Oh fantastic (look forward to going through them!) okay that's great - so is it just a case of fitting a Normal prior over a holiday beta and just passing in the index of 1's and 0's?

Or does this bit need to be changed so that it doesn't set the seasonal period to 0?

```python
# Dynamic regression
if design_matrix is not None:
    assert ps.rank(design_matrix) >= 2
    assert ps.shape(design_matrix)[-2] == observed.shape[-1]

    # seasonal adjustment
    if self.period > 0:
        warnings.warn("""
            Can not model seasonal difference with Dynamic regressions,
            Setting D to 0 ...
        """)
        self.period = 0

    self.design_matrix = tf.convert_to_tensor(
        np.diff(design_matrix, n=self.d, axis=0), dtype=dtype)
else:
    self.design_matrix = None
```

Many thanks again!

**Comment by junpenglao** [comment]
Yep that's where we should update it (removing the check and add period diff to the design_matrix)
AFAIK this is also how Statsmodel deal with SARIMAX (when you choose `simple_differencing=True`) https://github.com/statsmodels/statsmodels/blob/581119c64e43b6021bf247aa300b13abdfd5ef3b/statsmodels/tsa/statespace/sarimax.py#L551-L560

**Comment by elanmart** [comment]
Hi @junpenglao I know that this issue is closed, but maybe you have some extra reference on why seasonality + exogenous regressors is a tricky combination?

I was scratching my head over the "_Note that we can have either seasonal (SARIMA) or exogenous regressors (ARIMAX) but not both._" sentence for almost an hour 😃 

Why is it that you can't simply replace

$$
\begin{split}
y_t = \alpha + \sum_{i=1}^{p}\phi_i y_{t-period-i} + \sum_{j=1}^{q}\theta_j \epsilon_{t-period-j} + \epsilon_t
\end{split}
$$

with 

$$
\begin{split}
y_t = \mathbf{X} \beta + \sum_{i=1}^{p}\phi_i y_{t-period-i} + \sum_{j=1}^{q}\theta_j \epsilon_{t-period-j} + \epsilon_t
\end{split}
$$

**Comment by junpenglao** [comment]
Yeah that sentence is pretty confusing - what we are trying to say should be "_Usually_ we have either ... but not both". The reason being that it gets a bit confusing in interpretation with the interaction regressors and the seasonality (especially if the regressors contain some seasonal information). But you can definitely have both in your SARIMAX set up.
