### ISSUE TITLE
A bit confusion text P23

### ISSUE THREAD

**Issue by zhengchencai** [BayesianModelingandComputationInPython/BookCode_Edition1#141]
Hi there, 

I find the explanation of Laplace being a maximum entropy prior is confusing (page 23). Could you please explain what you mean by "an absolute value mean"? I thought the constrain here should be there is an existing absolute deviation to the mean (or more generally, the location). Thanks a lot.

**Comment by canyon289** [comment]
cc @aloctavodia

**Comment by aloctavodia** [comment]
Thanks @zhengchencai, I have updated the text.
