### ISSUE TITLE
Manuscript Error: Confusing  use of trace instead of idata in Fig. 1.5 plot

### ISSUE THREAD

**Issue by luxspes** [BayesianModelingandComputationInPython/BookCode_Edition1#144]
# Description
Confusing  use of `trace` instead of `idata` in Fig. 1.5 plot (img/chp01/Bayesian_quartet_distributions.png)

```
az.plot_dist(trace["θ"], plot_kwargs={"color":"0.5"},
             fill_kwargs={'alpha':1}, ax=axes[2])
```

works, but it is confusing because the variable "trace" was used on Code 1.3, and Fig 1.5 is meant to as result of Code 1.6, right?

I think it should be:

```
az.plot_dist(idata["posterior"]["θ"], plot_kwargs={"color":"0.5"},
             fill_kwargs={'alpha':1}, ax=axes[2])

```

**Reference**
Fig. 1.5 plot code

## Author Section
Do not close until

- [ ] Added to Errata
- [ ] Fixed in Open Access
- [ ] Fixed in latex source

**Comment by aloctavodia** [comment]
thanks @luxspes
