### ISSUE TITLE
Manuscript Error: Function argument not referenced in the code

### ISSUE THREAD

**Issue by azihna** [BayesianModelingandComputationInPython/BookCode_Edition1#147]
# Description
`input_df` parameter for the `gen_hierarchical_salad_sales` function on code block 4.13 not referenced inside the function. 
Expected:
```python
def gen_hierarchical_salad_sales(input_df, beta_prior_fn, dtype=tf.float32):
    customers = tf.constant(input_df["customers"].values, dtype=dtype)
    location_category = input_df["location"].values
    sales = tf.constant(input_df["sales"].values, dtype=dtype)
```

**Reference**
Page 133
https://bayesiancomputationbook.com/markdown/chp_04.html#model-hierarchical-salad-sales

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by canyon289** [comment]
@azihna Thanks for reporting this. We'll get it fixed!
