### ISSUE TITLE
Manuscript Error:

### ISSUE THREAD

**Issue by wmbelk** [BayesianModelingandComputationInPython/BookCode_Edition1#155]
navigation does not close on chapters 3, 5, & 10. 

# Description
 

navigation does not close on chapters 3, 5, & 10. 

**Reference**
 

https://bayesiancomputationbook.com/markdown/chp_03.html

https://bayesiancomputationbook.com/markdown/chp_05.html

https://bayesiancomputationbook.com/markdown/chp_10.html

## Author Section
Do not close until

- [ ] Added to Errata
- [ ] Fixed in Open Access
- [ ] Fixed in latex source

**Comment by aloctavodia** [comment]
Thanks for the report. It should be fixed now.

**Comment by wmbelk** [comment]
Absolutely.
Awesome book!
I ordered a hardback off Amazon.
