### ISSUE TITLE
Manuscript Error: SARIMA model equation

### ISSUE THREAD

**Issue by elanmart** [BayesianModelingandComputationInPython/BookCode_Edition1#176]
# Description

The formula in equation (6.9) seems to be inconsistent with the code implementing it

## Details

The equation (6.9) for Seasonal ARIMA states

$$
\begin{split}
y_t = \alpha + \sum_{i=1}^{p}\phi_i y_{t-period-i} + \sum_{j=1}^{q}\theta_j \epsilon_{t-period-j} + \epsilon_t
\end{split}
$$

But the code seems to be implementing

$$
\begin{split}
y_t = \alpha + \sum_{i=1}^{p}\phi_i y_{t-period \cdot i} + \sum_{j=1}^{q}\theta_j \epsilon_{t-period \cdot j} + \epsilon_t
\end{split}
$$

I.e. in the code the indices for seasonal components are given by `period * j` instead of `period - j`

The relevant piece of code is:
```python
sy_past = tf.gather(y_extended, t_shift - (np.arange(P) + 1) * period)
```

Apologies if I'm misinterpreting the formula / the code!

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by junpenglao** [comment]
You are right! It should be a multiplication. Thank you for spotting the mistake here.
