### ISSUE TITLE
Manuscript Errors: Chapter 1

### ISSUE THREAD

**Issue by behrouz-bakhtiari** [BayesianModelingandComputationInPython/BookCode_Edition1#183]
# Description
In the paragraph starting with "The Metropolis algorithm...", the word "are" needs to be removed in line 4.

**Reference**
page 7

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by canyon289** [comment]
Thank you for reporting these!
