### ISSUE TITLE
Missing dataset: 8M10 

### ISSUE THREAD

**Issue by opherdonchin** [BayesianModelingandComputationInPython/BookCode_Edition1#201]
# Description
 

The data set `Lotka-Voltera_00` referenced in problem 8M10 seems to be missing from the `Exercises/data` folder.

**Reference**
 
Page 258. [https://bayesiancomputationbook.com/markdown/chp_08.html#exercises](https://bayesiancomputationbook.com/markdown/chp_08.html#exercises)

## Author Section
Do not close until

- [ ] Added to Errata
- [ ] Fixed in Open Access
- [ ] Fixed in latex source

**Comment by opherdonchin** [comment]
Sorry: also the simulator mentioned in the problem seems to be missing.

**Comment by aloctavodia** [comment]
I am really sorry, I can't find the files on my computer, they may be on my old laptop or a backup disk. It may take me one or two days to find the files, in the meantime, you can explore this notebook https://docs.pymc.io/en/v3/pymc-examples/examples/samplers/SMC-ABC_Lotka-Volterra_example.html#Lotka%E2%80%93Volterra that was the inspiration for exercises 8M10 and 8M11.

**Comment by opherdonchin** [comment]
That's a big help. I gave the exercise to students as part of an end-of-semester poject. I should have checked ahead of time. Anyway, they should be able to get what they need from here. If you do find (or re-generate) an appropriate set of files, I'll be happy to pass them on.

Opher

**Comment by canyon289** [comment]
@opherdonchin its on us to have provided them. Thank you for your patience while we fix things.

If you dont mind me asking what kind of class are you teaching? Would love to get more feedback on how we can improve things for you and your students

**Comment by opherdonchin** [comment]
Hi. Thanks for all the help!

Briefly, it's a graduate level course primarily aimed at biomedical engineering students who had a semester of frequentist statistics as undergrads (also taught by me). I'm happy to share the syllabus and also quite happy to discuss. It's not easy figuring out exactly what to teach.

Opher

**Comment by aloctavodia** [comment]
I am really, really sorry. The file is here https://github.com/BayesianModelingandComputationInPython/BookCode_Edition1/blob/main/exercises/data/Lotka-Voltera_00.csv

**Comment by opherdonchin** [comment]
Thanks so much! 

I've really enjoyed teaching from the book. I combine it with Bayesian Analysis With Python and Statistical Rethinking and jump back and forth between them. I find the computational depth and the quality of the exercises in your book to be really excellent.

Opher
