### ISSUE TITLE
Manuscript Error:

### ISSUE THREAD

**Issue by OmriTreidel** [BayesianModelingandComputationInPython/BookCode_Edition1#213]
# Description
In Chapter 1 the solution for 1H.23 seems to be wrong.  From a logical point of view, since 3 out of 5 days are sunny (the example data),  one expects the theta to be centred around 3/5=0.6 and not around 0.15 and shown in the solution. 

I think that the error is in the line 

```y_obs = pm.Binomial("y_obs", n=5, p=θ, observed=weather_obs)``` 

Since the data is an array of 0,1 I think it should be `pm.Bernoulli` instead which gives the expected answer.  The complete code block should be

```
# Weather from one of the authors 0 is sunny, 1 is cloudly
weather_obs = [0, 1, 1, 0, 1]

with pm.Model() as model:
    # Specify the prior distribution of unknown parameter
    θ = pm.Beta("θ", alpha=1, beta=1)
    
    # Specify the likelihood distribution and condition on the observed data
    y_obs = pm.Bernoulli("y_obs", p=θ, observed=weather_obs)
    # Sample from the posterior distribution
    trace = pm.sample(1000, return_inferencedata=True)
    post_pred = pm.sample_posterior_predictive(trace)
```

**Reference**
 
N/A since I don't have the physical book. 

## Author Section
Do not close until

- [ ] Added to Errata
- [ ] Fixed in Open Access
- [ ] Fixed in latex source

**Comment by canyon289** [comment]
Thanks for the report. For this one either bernoulli or binomial will work as a bernoulli is a single trial and binomial is multiple trials. Under the hood pymc will convert them to the same calculation if multiple bernoullis are observed

**Comment by OmriTreidel** [comment]
Thanks for the quick reply @canyon289. 

If this is the case there must be some other error since  the the HDI of theta is [0.037, 0.27] which is very far the exact solution Beta(alpha = 3 +1,  beta=5 - 3 + 1) = Beta(4, 3) which has its maximum at 0.6. 

When running the code block I mentioned above the posterior of theta looks just like Beta(4, 3)

**Comment by OmriTreidel** [comment]
I'm happy to make a PR if you like
