### ISSUE TITLE
Typo on page /markdown/chp_09.html#observational-studies

### ISSUE THREAD

**Issue by daniel-wells** [BayesianModelingandComputationInPython/BookCode_Edition1#67]
I believe the first sentence of the Observational Studies section is missing a "that" i.e. it should read:
"Farming your own ingredients can be expensive, so a cheaper alternative could be foraging for ingredients **that** are growing by themselves."
Instead of:
"Farming your own ingredients can be expensive, so a cheaper alternative could be foraging for ingredients are growing by themselves."

**Comment by canyon289** [comment]
Thanks for reporting! We're on it

**Comment by canyon289** [comment]
We need to add to errata
