### ISSUE TITLE
Manuscript Error: Units missing

### ISSUE THREAD

**Issue by juanitorduz** [BayesianModelingandComputationInPython/BookCode_Edition1#84]
Hey! I love the book! Thanks for working on it :) 

# Description

In Section 9.11 [Experimental Example: Comparing Between Two Groups](https://bayesiancomputationbook.com/markdown/chp_09.html#experimental-example-comparing-between-two-groups) I think there are missing units. I quote:
*... For example, the first bidirectional specimen failed at 3774 lbf (1532 kg) at a cross section area of .504 inches (12.8mm) by .057 inches (1.27), yielding an ultimate strength of 131.393 ksi (kilopound per square inch). *

However it seems it should be:

*...For example, the first bidirectional specimen failed at 3774 lbf (1532 kg) at a cross section area of .504 inches (12.8mm) by .057 inches (1.27mm), yielding an ultimate strength of 131.393 ksi (kilopound per square inch). *

Note the change in **(1.27mm)**

**Reference**

Section 9.11 [Experimental Example: Comparing Between Two Groups](https://bayesiancomputationbook.com/markdown/chp_09.html#experimental-example-comparing-between-two-groups). In the book is page 286.

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by aloctavodia** [comment]
thanks @juanitorduz !
