### ISSUE TITLE
Manuscript Error: Missing parentheses

### ISSUE THREAD

**Issue by juanitorduz** [BayesianModelingandComputationInPython/BookCode_Edition1#85]
# Description

In Section 2.4.1 [Effective Sample Size](https://bayesiancomputationbook.com/markdown/chp_02.html#effective-sample-size)
there is a parentheses missing (page 42 physical book). I quote:
*Plotting the ESS for specifics quantiles `az.plot_ess(., kind="quantiles"` or for small intervals*
I think it should be 
*Plotting the ESS for specifics quantiles `az.plot_ess(., kind="quantiles")` or for small intervals*
Note the closed parentheses in the `az.plot_ess` method.

**Reference**
Section 2.4.1 [Effective Sample Size](https://bayesiancomputationbook.com/markdown/chp_02.html#effective-sample-size)
 and page 42 physical book.

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by aloctavodia** [comment]
thanks @juanitorduz !
