### ISSUE TITLE
Open Access Figure numbers don't match the printed book

### ISSUE THREAD

**Issue by canyon289** [BayesianModelingandComputationInPython/BookCode_Edition1#90]
It'd be nice if they did

<img width="904" alt="image" src="https://user-images.githubusercontent.com/7213793/149641453-ff43e79c-fdb6-4ce4-8493-4ac8508c4f55.png">

**Comment by aloctavodia** [comment]
The same goes for all numbered cross-references, tables and mathematical expressions. And on the online version code blocks are refereced by name not numbers.
