### ISSUE TITLE
Manuscript Error: skweness

### ISSUE THREAD

**Issue by azihna** [BayesianModelingandComputationInPython/BookCode_Edition1#93]
# Description
 
Typo in writing skewness on page 344 of the book under Appendiceal Topics, linked below.

**Reference**
https://bayesiancomputationbook.com/markdown/chp_11.html#:~:text=it%20will%20make%20the%20skweness%20independent
Page 344 line 4
 

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by aloctavodia** [comment]
Thanks @azihna
