### ISSUE TITLE
Manuscript Error: Typo on page 376 and 380

### ISSUE THREAD

**Issue by azihna** [BayesianModelingandComputationInPython/BookCode_Edition1#95]
# Description
 
Broken sentence on 376 and Typo on 380

**Reference**
 
376:
https://bayesiancomputationbook.com/markdown/chp_11.html#:~:text=kind%20these%20divergences-,and%20we%20can%20used%20as,-diagnostics%20of%20the

380:
https://bayesiancomputationbook.com/markdown/chp_11.html#:~:text=with%20programming%20languages%2C-,if%20you%20future,-lab%20group%20uses

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by canyon289** [comment]
Thanks for reporting. We're on it
