### ISSUE TITLE
Manuscript Error: Typo in Fig 36

### ISSUE THREAD

**Issue by jroberayalas** [BayesianModelingandComputationInPython/BookCode_Edition1#96]
# Description
Figure 36 has the following description:

> Fig. 36 Forest plot of the mean of mass of each species group in model_penguin_mass_all_species. Each line represents one chain in the sampler, the dot is a point estimate, in this case the mean, the _thin_ line is the interquartile range from 25% to 75% of the posterior and the _thick_ line is the 94% Highest Density Interval.

However, from the plot, it does not make sense since the thin line is larger than the thick line which would mean that the 50% interquartile range contains 94% of the data. I think the _thin_ and _thick_ descriptors should be reverted.

**Reference**
https://bayesiancomputationbook.com/markdown/chp_03.html#comparing-two-or-more-groups

## Author Section
Do not close until

- [x] Added to Errata
- [x] Fixed in Open Access
- [x] Fixed in latex source

**Comment by canyon289** [comment]
Thanks for reporting. I'm also noticing that I should fix a couple of things in ArviZ as well, appreciate you pointing this out
